### ISSUE TITLE
Allow overriding the serializer used by the JSON renderer

### ISSUE THREAD

**Issue by petemounce** [multani/structlog-gcp#28]
https://www.structlog.org/en/stable/performance.html recommends using a more performant JSON serializer than stdlib's. It would be great to allow passing that into the `FormatAsCloudLogging`.

**Comment by multani** [comment]
@petemounce I released the change in https://github.com/multani/structlog-gcp/releases/tag/v0.2.4 :tada:

**Comment by multani** [comment]
@petemounce FYI, I released https://github.com/multani/structlog-gcp/releases/tag/v0.3.0 which provides a new builder function that *doesn't* configure the JSON renderer by default and focus exclusively on the GCP-specific processors.

See the ["Advanced Configuration"](https://github.com/multani/structlog-gcp?tab=readme-ov-file#advanced-configuration) doc, where I show an example on how to use it and how to pass an explicit JSON renderer.
