### ISSUE TITLE
structlog contextvars support?

### ISSUE THREAD

**Issue by blakewatters** [multani/structlog-gcp#33]
In my application it looks like key-value pairs attached via structlog's contextvar support make it into the GCP payload. It would be nice to merge these values in as supplemental metadata on the statement emitted to GCL

I'm new to the structlog codebase but will take a look and see about adding support

**Comment by blakewatters** [comment]
Fixed by adding this:

```python
processors = structlog_gcp.build_processors()
processors.insert(0, structlog.contextvars.merge_contextvars)
structlog.configure(processors=processors)
```

Arguably you should add this as the default since I can't really see any downside and that's how the default processors are setup out of the box

**Comment by multani** [comment]
> In my application it looks like key-value pairs attached via structlog's contextvar support make it into the GCP payload. It would be nice to merge these values in as supplemental metadata on the statement emitted to GCL

Do you have an example of what you are logging and how it outputs?

I will check how to add the context vars processor ; I wanted to split the initialization anyway between the GCP specific part (for those who want to have their own processors before/after) and a one-line function that does the right stuff ® for those who only want the default configuration.

**Comment by multani** [comment]
@blakewatters I released https://github.com/multani/structlog-gcp/releases/tag/v0.3.0 which provides context variables support by default.

If you were using this before:

```python
processors = structlog_gcp.build_processors()
processors.insert(0, structlog.contextvars.merge_contextvars)
structlog.configure(processors=processors)
```

... you can now upgrade to >= v0.3.0 and replace this by:

```python
processors = structlog_gcp.build_processors()
structlog.configure(processors=processors)
```

Hope it helps!
